version: "3.2"

services:
  backend:
    image: node:10-alpine
    volumes:
      - .:/server
    command: sh -c 'cd server && yarn && yarn start:dev'
    environment:
      MONGO_URL: mongodb://db/cgrader
      GCLOUD_PROJECT_ID:
      GCLOUD_APP_CREDENTIALS:
      GCLOUD_BUCKET_NAME:
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: cgrader-db
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
      - ./volumes/mongodb_config:/data/configdb