version: 2
jobs:
  run_test:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - run:
          name: run test
          command: yarn test
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_test
